export type Decade = '50s' | '60s' | '70s' | '80s' | '90s' | '2000s' | '2010s' | '2020s';

export interface DriverData {
  id: string;
  fullName: string;
  givenName: string;
  familyName: string;
  nationality: string;       // display label e.g. 'Spanish'
  nationalityCode: string;   // ISO 3166-1 alpha-2 e.g. 'es'
  teams: string[];           // human-readable, use KNOWN_TEAM_IDS keys
  isChampion: boolean;
  winsAtLeastOne: boolean;
  totalWins: number;
  totalGPs: number;
  decades: Decade[];
  isLatam: boolean;
  wikipediaName: string;
}

// Maps human-readable team names → CONSTRUCTOR_POOL ids
export const TEAM_NAME_TO_ID: Record<string, string> = {
  'Ferrari':       'ferrari',
  'McLaren':       'mclaren',
  'Williams':      'williams',
  'Renault':       'renault',
  'Red Bull':      'red_bull',
  'Mercedes':      'mercedes',
  'Alpine':        'alpine',
  'Alfa Romeo':    'alfa_romeo',
  'Sauber':        'alfa_romeo',   // same pool slot
  'Haas':          'haas',
  'AlphaTauri':    'alphatauri',
  'Aston Martin':  'aston_martin',
  'Lotus':         'lotus_f1',
  'Brabham':       'brabham',
  'Tyrrell':       'tyrrell',
  'Jordan':        'jordan',
  'BAR':           'bar',
  'Honda':         'bar',          // BAR became Honda F1 2006-2008
  'BMW Sauber':    'bmw_sauber',
  'Force India':   'force_india',
  'Toro Rosso':    'toro_rosso',
  'Benetton':      'benetton',
};

// ---------------------------------------------------------------------------
// Driver dataset — 70+ drivers, all fields manually verified
// ---------------------------------------------------------------------------
export const DRIVERS: DriverData[] = [
  // ── Current/recent era ────────────────────────────────────────────────────
  {
    id: 'hamilton', fullName: 'Lewis Hamilton', givenName: 'Lewis', familyName: 'Hamilton',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['McLaren', 'Mercedes', 'Ferrari'],
    isChampion: true, winsAtLeastOne: true, totalWins: 103, totalGPs: 354,
    decades: ['2000s', '2010s', '2020s'], isLatam: false,
    wikipediaName: 'Lewis_Hamilton',
  },
  {
    id: 'max_verstappen', fullName: 'Max Verstappen', givenName: 'Max', familyName: 'Verstappen',
    nationality: 'Dutch', nationalityCode: 'nl',
    teams: ['Toro Rosso', 'Red Bull'],
    isChampion: true, winsAtLeastOne: true, totalWins: 61, totalGPs: 202,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Max_Verstappen',
  },
  {
    id: 'leclerc', fullName: 'Charles Leclerc', givenName: 'Charles', familyName: 'Leclerc',
    nationality: 'Monegasque', nationalityCode: 'mc',
    teams: ['Alfa Romeo', 'Ferrari'],
    isChampion: false, winsAtLeastOne: true, totalWins: 8, totalGPs: 168,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Charles_Leclerc',
  },
  {
    id: 'sainz', fullName: 'Carlos Sainz', givenName: 'Carlos', familyName: 'Sainz',
    nationality: 'Spanish', nationalityCode: 'es',
    teams: ['Toro Rosso', 'Renault', 'McLaren', 'Ferrari', 'Williams'],
    isChampion: false, winsAtLeastOne: true, totalWins: 3, totalGPs: 209,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Carlos_Sainz_Jr.',
  },
  {
    id: 'norris', fullName: 'Lando Norris', givenName: 'Lando', familyName: 'Norris',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['McLaren'],
    isChampion: false, winsAtLeastOne: true, totalWins: 4, totalGPs: 128,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Lando_Norris',
  },
  {
    id: 'russell', fullName: 'George Russell', givenName: 'George', familyName: 'Russell',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Williams', 'Mercedes'],
    isChampion: false, winsAtLeastOne: true, totalWins: 2, totalGPs: 128,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'George_Russell_(racing_driver)',
  },
  {
    id: 'piastri', fullName: 'Oscar Piastri', givenName: 'Oscar', familyName: 'Piastri',
    nationality: 'Australian', nationalityCode: 'au',
    teams: ['McLaren'],
    isChampion: false, winsAtLeastOne: true, totalWins: 3, totalGPs: 48,
    decades: ['2020s'], isLatam: false,
    wikipediaName: 'Oscar_Piastri',
  },
  {
    id: 'perez', fullName: 'Sergio Pérez', givenName: 'Sergio', familyName: 'Pérez',
    nationality: 'Mexican', nationalityCode: 'mx',
    teams: ['Sauber', 'McLaren', 'Force India', 'Red Bull'],
    isChampion: false, winsAtLeastOne: true, totalWins: 13, totalGPs: 281,
    decades: ['2010s', '2020s'], isLatam: true,
    wikipediaName: 'Sergio_Pérez',
  },
  {
    id: 'bottas', fullName: 'Valtteri Bottas', givenName: 'Valtteri', familyName: 'Bottas',
    nationality: 'Finnish', nationalityCode: 'fi',
    teams: ['Williams', 'Mercedes', 'Alfa Romeo'],
    isChampion: false, winsAtLeastOne: true, totalWins: 10, totalGPs: 243,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Valtteri_Bottas',
  },
  {
    id: 'ricciardo', fullName: 'Daniel Ricciardo', givenName: 'Daniel', familyName: 'Ricciardo',
    nationality: 'Australian', nationalityCode: 'au',
    teams: ['Toro Rosso', 'Red Bull', 'Renault', 'McLaren', 'AlphaTauri'],
    isChampion: false, winsAtLeastOne: true, totalWins: 8, totalGPs: 260,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Daniel_Ricciardo',
  },
  {
    id: 'gasly', fullName: 'Pierre Gasly', givenName: 'Pierre', familyName: 'Gasly',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Toro Rosso', 'Red Bull', 'AlphaTauri', 'Alpine'],
    isChampion: false, winsAtLeastOne: true, totalWins: 1, totalGPs: 154,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Pierre_Gasly',
  },
  {
    id: 'ocon', fullName: 'Esteban Ocon', givenName: 'Esteban', familyName: 'Ocon',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Force India', 'Renault', 'Alpine'],
    isChampion: false, winsAtLeastOne: true, totalWins: 1, totalGPs: 120,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Esteban_Ocon',
  },
  {
    id: 'albon', fullName: 'Alexander Albon', givenName: 'Alexander', familyName: 'Albon',
    nationality: 'Thai', nationalityCode: 'th',
    teams: ['Toro Rosso', 'Red Bull', 'Williams'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 113,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Alexander_Albon',
  },
  {
    id: 'stroll', fullName: 'Lance Stroll', givenName: 'Lance', familyName: 'Stroll',
    nationality: 'Canadian', nationalityCode: 'ca',
    teams: ['Williams', 'Force India', 'Aston Martin'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 168,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Lance_Stroll',
  },
  {
    id: 'tsunoda', fullName: 'Yuki Tsunoda', givenName: 'Yuki', familyName: 'Tsunoda',
    nationality: 'Japanese', nationalityCode: 'jp',
    teams: ['AlphaTauri', 'Red Bull'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 96,
    decades: ['2020s'], isLatam: false,
    wikipediaName: 'Yuki_Tsunoda',
  },
  {
    id: 'hulkenberg', fullName: 'Nico Hülkenberg', givenName: 'Nico', familyName: 'Hülkenberg',
    nationality: 'German', nationalityCode: 'de',
    teams: ['Williams', 'Force India', 'Sauber', 'Renault', 'Haas'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 232,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Nico_Hülkenberg',
  },
  {
    id: 'magnussen', fullName: 'Kevin Magnussen', givenName: 'Kevin', familyName: 'Magnussen',
    nationality: 'Danish', nationalityCode: 'dk',
    teams: ['McLaren', 'Renault', 'Haas'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 180,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Kevin_Magnussen',
  },
  {
    id: 'giovinazzi', fullName: 'Antonio Giovinazzi', givenName: 'Antonio', familyName: 'Giovinazzi',
    nationality: 'Italian', nationalityCode: 'it',
    teams: ['Alfa Romeo'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 62,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Antonio_Giovinazzi',
  },
  {
    id: 'schumacher_m', fullName: 'Mick Schumacher', givenName: 'Mick', familyName: 'Schumacher',
    nationality: 'German', nationalityCode: 'de',
    teams: ['Haas'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 43,
    decades: ['2020s'], isLatam: false,
    wikipediaName: 'Mick_Schumacher',
  },
  {
    id: 'colapinto', fullName: 'Franco Colapinto', givenName: 'Franco', familyName: 'Colapinto',
    nationality: 'Argentine', nationalityCode: 'ar',
    teams: ['Williams', 'Alpine'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 13,
    decades: ['2020s'], isLatam: true,
    wikipediaName: 'Franco_Colapinto',
  },
  {
    id: 'kvyat', fullName: 'Daniil Kvyat', givenName: 'Daniil', familyName: 'Kvyat',
    nationality: 'Russian', nationalityCode: 'ru',
    teams: ['Toro Rosso', 'Red Bull', 'AlphaTauri'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 110,
    decades: ['2010s', '2020s'], isLatam: false,
    wikipediaName: 'Daniil_Kvyat',
  },
  {
    id: 'grosjean', fullName: 'Romain Grosjean', givenName: 'Romain', familyName: 'Grosjean',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Renault', 'Lotus', 'Haas'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 179,
    decades: ['2000s', '2010s'], isLatam: false,
    wikipediaName: 'Romain_Grosjean',
  },
  {
    id: 'maldonado', fullName: 'Pastor Maldonado', givenName: 'Pastor', familyName: 'Maldonado',
    nationality: 'Venezuelan', nationalityCode: 've',
    teams: ['Williams', 'Lotus'],
    isChampion: false, winsAtLeastOne: true, totalWins: 1, totalGPs: 101,
    decades: ['2010s'], isLatam: true,
    wikipediaName: 'Pastor_Maldonado',
  },
  {
    id: 'gutierrez_e', fullName: 'Esteban Gutiérrez', givenName: 'Esteban', familyName: 'Gutiérrez',
    nationality: 'Mexican', nationalityCode: 'mx',
    teams: ['Sauber', 'Haas'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 59,
    decades: ['2010s'], isLatam: true,
    wikipediaName: 'Esteban_Gutiérrez',
  },
  // ── 2000s era ─────────────────────────────────────────────────────────────
  {
    id: 'alonso', fullName: 'Fernando Alonso', givenName: 'Fernando', familyName: 'Alonso',
    nationality: 'Spanish', nationalityCode: 'es',
    teams: ['Renault', 'McLaren', 'Ferrari', 'Alpine', 'Aston Martin'],
    isChampion: true, winsAtLeastOne: true, totalWins: 32, totalGPs: 373,
    decades: ['2000s', '2010s', '2020s'], isLatam: false,
    wikipediaName: 'Fernando_Alonso_(racing_driver)',
  },
  {
    id: 'vettel', fullName: 'Sebastian Vettel', givenName: 'Sebastian', familyName: 'Vettel',
    nationality: 'German', nationalityCode: 'de',
    teams: ['BMW Sauber', 'Toro Rosso', 'Red Bull', 'Ferrari', 'Aston Martin'],
    isChampion: true, winsAtLeastOne: true, totalWins: 53, totalGPs: 299,
    decades: ['2000s', '2010s', '2020s'], isLatam: false,
    wikipediaName: 'Sebastian_Vettel',
  },
  {
    id: 'raikkonen', fullName: 'Kimi Räikkönen', givenName: 'Kimi', familyName: 'Räikkönen',
    nationality: 'Finnish', nationalityCode: 'fi',
    teams: ['Sauber', 'McLaren', 'Ferrari', 'Lotus', 'Ferrari', 'Alfa Romeo'],
    isChampion: true, winsAtLeastOne: true, totalWins: 21, totalGPs: 349,
    decades: ['2000s', '2010s', '2020s'], isLatam: false,
    wikipediaName: 'Kimi_Räikkönen',
  },
  {
    id: 'schumacher', fullName: 'Michael Schumacher', givenName: 'Michael', familyName: 'Schumacher',
    nationality: 'German', nationalityCode: 'de',
    teams: ['Jordan', 'Benetton', 'Ferrari', 'Mercedes'],
    isChampion: true, winsAtLeastOne: true, totalWins: 91, totalGPs: 308,
    decades: ['90s', '2000s', '2010s'], isLatam: false,
    wikipediaName: 'Michael_Schumacher',
  },
  {
    id: 'button', fullName: 'Jenson Button', givenName: 'Jenson', familyName: 'Button',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Williams', 'Benetton', 'BAR', 'Honda', 'McLaren'],
    isChampion: true, winsAtLeastOne: true, totalWins: 15, totalGPs: 306,
    decades: ['2000s', '2010s'], isLatam: false,
    wikipediaName: 'Jenson_Button',
  },
  {
    id: 'rosberg', fullName: 'Nico Rosberg', givenName: 'Nico', familyName: 'Rosberg',
    nationality: 'German', nationalityCode: 'de',
    teams: ['Williams', 'Mercedes'],
    isChampion: true, winsAtLeastOne: true, totalWins: 23, totalGPs: 206,
    decades: ['2000s', '2010s'], isLatam: false,
    wikipediaName: 'Nico_Rosberg',
  },
  {
    id: 'webber', fullName: 'Mark Webber', givenName: 'Mark', familyName: 'Webber',
    nationality: 'Australian', nationalityCode: 'au',
    teams: ['Williams', 'Red Bull'],
    isChampion: false, winsAtLeastOne: true, totalWins: 9, totalGPs: 215,
    decades: ['2000s', '2010s'], isLatam: false,
    wikipediaName: 'Mark_Webber_(racing_driver)',
  },
  {
    id: 'barrichello', fullName: 'Rubens Barrichello', givenName: 'Rubens', familyName: 'Barrichello',
    nationality: 'Brazilian', nationalityCode: 'br',
    teams: ['Jordan', 'Ferrari', 'BAR', 'Honda', 'Williams'],
    isChampion: false, winsAtLeastOne: true, totalWins: 11, totalGPs: 326,
    decades: ['90s', '2000s', '2010s'], isLatam: true,
    wikipediaName: 'Rubens_Barrichello',
  },
  {
    id: 'massa', fullName: 'Felipe Massa', givenName: 'Felipe', familyName: 'Massa',
    nationality: 'Brazilian', nationalityCode: 'br',
    teams: ['Sauber', 'Ferrari', 'Williams'],
    isChampion: false, winsAtLeastOne: true, totalWins: 11, totalGPs: 269,
    decades: ['2000s', '2010s'], isLatam: true,
    wikipediaName: 'Felipe_Massa',
  },
  {
    id: 'montoya', fullName: 'Juan Pablo Montoya', givenName: 'Juan Pablo', familyName: 'Montoya',
    nationality: 'Colombian', nationalityCode: 'co',
    teams: ['Williams', 'McLaren'],
    isChampion: false, winsAtLeastOne: true, totalWins: 7, totalGPs: 95,
    decades: ['2000s'], isLatam: true,
    wikipediaName: 'Juan_Pablo_Montoya',
  },
  {
    id: 'coulthard', fullName: 'David Coulthard', givenName: 'David', familyName: 'Coulthard',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Williams', 'McLaren', 'Red Bull'],
    isChampion: false, winsAtLeastOne: true, totalWins: 13, totalGPs: 247,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'David_Coulthard',
  },
  {
    id: 'kubica', fullName: 'Robert Kubica', givenName: 'Robert', familyName: 'Kubica',
    nationality: 'Polish', nationalityCode: 'pl',
    teams: ['BMW Sauber', 'Renault', 'Williams'],
    isChampion: false, winsAtLeastOne: true, totalWins: 1, totalGPs: 99,
    decades: ['2000s', '2010s'], isLatam: false,
    wikipediaName: 'Robert_Kubica',
  },
  {
    id: 'heidfeld', fullName: 'Nick Heidfeld', givenName: 'Nick', familyName: 'Heidfeld',
    nationality: 'German', nationalityCode: 'de',
    teams: ['Williams', 'Sauber', 'BMW Sauber', 'Renault'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 183,
    decades: ['2000s', '2010s'], isLatam: false,
    wikipediaName: 'Nick_Heidfeld',
  },
  {
    id: 'kovalainen', fullName: 'Heikki Kovalainen', givenName: 'Heikki', familyName: 'Kovalainen',
    nationality: 'Finnish', nationalityCode: 'fi',
    teams: ['Renault', 'McLaren'],
    isChampion: false, winsAtLeastOne: true, totalWins: 1, totalGPs: 111,
    decades: ['2000s', '2010s'], isLatam: false,
    wikipediaName: 'Heikki_Kovalainen',
  },
  {
    id: 'sutil', fullName: 'Adrian Sutil', givenName: 'Adrian', familyName: 'Sutil',
    nationality: 'German', nationalityCode: 'de',
    teams: ['Force India', 'Sauber'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 128,
    decades: ['2000s', '2010s'], isLatam: false,
    wikipediaName: 'Adrian_Sutil',
  },
  {
    id: 'sato_t', fullName: 'Takuma Sato', givenName: 'Takuma', familyName: 'Sato',
    nationality: 'Japanese', nationalityCode: 'jp',
    teams: ['Jordan', 'BAR'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 90,
    decades: ['2000s'], isLatam: false,
    wikipediaName: 'Takuma_Sato',
  },
  {
    id: 'piquet_jr', fullName: 'Nelson Piquet Jr.', givenName: 'Nelson', familyName: 'Piquet Jr.',
    nationality: 'Brazilian', nationalityCode: 'br',
    teams: ['Renault', 'Williams'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 28,
    decades: ['2000s'], isLatam: true,
    wikipediaName: 'Nelson_Piquet_Jr.',
  },
  {
    id: 'de_la_rosa', fullName: 'Pedro de la Rosa', givenName: 'Pedro', familyName: 'de la Rosa',
    nationality: 'Spanish', nationalityCode: 'es',
    teams: ['McLaren', 'Sauber'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 104,
    decades: ['90s', '2000s', '2010s'], isLatam: false,
    wikipediaName: 'Pedro_de_la_Rosa',
  },
  // ── 90s era ───────────────────────────────────────────────────────────────
  {
    id: 'hakkinen', fullName: 'Mika Häkkinen', givenName: 'Mika', familyName: 'Häkkinen',
    nationality: 'Finnish', nationalityCode: 'fi',
    teams: ['Lotus', 'McLaren'],
    isChampion: true, winsAtLeastOne: true, totalWins: 20, totalGPs: 165,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'Mika_Häkkinen',
  },
  {
    id: 'hill', fullName: 'Damon Hill', givenName: 'Damon', familyName: 'Hill',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Williams', 'Jordan'],
    isChampion: true, winsAtLeastOne: true, totalWins: 22, totalGPs: 122,
    decades: ['90s'], isLatam: false,
    wikipediaName: 'Damon_Hill',
  },
  {
    id: 'villeneuve', fullName: 'Jacques Villeneuve', givenName: 'Jacques', familyName: 'Villeneuve',
    nationality: 'Canadian', nationalityCode: 'ca',
    teams: ['Williams', 'BAR', 'Renault', 'BMW Sauber'],
    isChampion: true, winsAtLeastOne: true, totalWins: 11, totalGPs: 163,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'Jacques_Villeneuve',
  },
  {
    id: 'fisichella', fullName: 'Giancarlo Fisichella', givenName: 'Giancarlo', familyName: 'Fisichella',
    nationality: 'Italian', nationalityCode: 'it',
    teams: ['Jordan', 'Benetton', 'Renault', 'Force India', 'Ferrari'],
    isChampion: false, winsAtLeastOne: true, totalWins: 3, totalGPs: 229,
    decades: ['90s', '2000s', '2010s'], isLatam: false,
    wikipediaName: 'Giancarlo_Fisichella',
  },
  {
    id: 'trulli', fullName: 'Jarno Trulli', givenName: 'Jarno', familyName: 'Trulli',
    nationality: 'Italian', nationalityCode: 'it',
    teams: ['Minardi', 'Jordan', 'Renault', 'Toyota'],
    isChampion: false, winsAtLeastOne: true, totalWins: 1, totalGPs: 252,
    decades: ['90s', '2000s', '2010s'], isLatam: false,
    wikipediaName: 'Jarno_Trulli',
  },
  {
    id: 'frentzen', fullName: 'Heinz-Harald Frentzen', givenName: 'Heinz-Harald', familyName: 'Frentzen',
    nationality: 'German', nationalityCode: 'de',
    teams: ['Sauber', 'Williams', 'Jordan'],
    isChampion: false, winsAtLeastOne: true, totalWins: 3, totalGPs: 157,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'Heinz-Harald_Frentzen',
  },
  {
    id: 'irvine', fullName: 'Eddie Irvine', givenName: 'Eddie', familyName: 'Irvine',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Jordan', 'Ferrari'],
    isChampion: false, winsAtLeastOne: true, totalWins: 4, totalGPs: 146,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'Eddie_Irvine',
  },
  {
    id: 'herbert', fullName: 'Johnny Herbert', givenName: 'Johnny', familyName: 'Herbert',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Benetton', 'Ferrari', 'Williams'],
    isChampion: false, winsAtLeastOne: true, totalWins: 3, totalGPs: 162,
    decades: ['90s'], isLatam: false,
    wikipediaName: 'Johnny_Herbert',
  },
  {
    id: 'panis', fullName: 'Olivier Panis', givenName: 'Olivier', familyName: 'Panis',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['McLaren', 'BAR'],
    isChampion: false, winsAtLeastOne: true, totalWins: 1, totalGPs: 157,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'Olivier_Panis',
  },
  {
    id: 'ralf_schumacher', fullName: 'Ralf Schumacher', givenName: 'Ralf', familyName: 'Schumacher',
    nationality: 'German', nationalityCode: 'de',
    teams: ['Jordan', 'Williams', 'Toyota'],
    isChampion: false, winsAtLeastOne: true, totalWins: 6, totalGPs: 180,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'Ralf_Schumacher',
  },
  // ── 80s/90s era ───────────────────────────────────────────────────────────
  {
    id: 'senna', fullName: 'Ayrton Senna', givenName: 'Ayrton', familyName: 'Senna',
    nationality: 'Brazilian', nationalityCode: 'br',
    teams: ['Lotus', 'McLaren', 'Williams'],
    isChampion: true, winsAtLeastOne: true, totalWins: 41, totalGPs: 162,
    decades: ['80s', '90s'], isLatam: true,
    wikipediaName: 'Ayrton_Senna',
  },
  {
    id: 'prost', fullName: 'Alain Prost', givenName: 'Alain', familyName: 'Prost',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Renault', 'McLaren', 'Ferrari', 'Williams'],
    isChampion: true, winsAtLeastOne: true, totalWins: 51, totalGPs: 202,
    decades: ['80s', '90s'], isLatam: false,
    wikipediaName: 'Alain_Prost',
  },
  {
    id: 'mansell', fullName: 'Nigel Mansell', givenName: 'Nigel', familyName: 'Mansell',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Lotus', 'Williams', 'Ferrari'],
    isChampion: true, winsAtLeastOne: true, totalWins: 31, totalGPs: 187,
    decades: ['80s', '90s'], isLatam: false,
    wikipediaName: 'Nigel_Mansell',
  },
  {
    id: 'piquet', fullName: 'Nelson Piquet', givenName: 'Nelson', familyName: 'Piquet',
    nationality: 'Brazilian', nationalityCode: 'br',
    teams: ['Brabham', 'Williams', 'Ferrari'],
    isChampion: true, winsAtLeastOne: true, totalWins: 23, totalGPs: 204,
    decades: ['80s', '90s'], isLatam: true,
    wikipediaName: 'Nelson_Piquet',
  },
  {
    id: 'berger', fullName: 'Gerhard Berger', givenName: 'Gerhard', familyName: 'Berger',
    nationality: 'Austrian', nationalityCode: 'at',
    teams: ['Ferrari', 'McLaren', 'Benetton'],
    isChampion: false, winsAtLeastOne: true, totalWins: 10, totalGPs: 210,
    decades: ['80s', '90s'], isLatam: false,
    wikipediaName: 'Gerhard_Berger',
  },
  {
    id: 'alesi', fullName: 'Jean Alesi', givenName: 'Jean', familyName: 'Alesi',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Tyrrell', 'Ferrari', 'Benetton'],
    isChampion: false, winsAtLeastOne: true, totalWins: 1, totalGPs: 201,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'Jean_Alesi',
  },
  {
    id: 'lauda', fullName: 'Niki Lauda', givenName: 'Niki', familyName: 'Lauda',
    nationality: 'Austrian', nationalityCode: 'at',
    teams: ['Brabham', 'Ferrari', 'McLaren'],
    isChampion: true, winsAtLeastOne: true, totalWins: 25, totalGPs: 171,
    decades: ['70s', '80s'], isLatam: false,
    wikipediaName: 'Niki_Lauda',
  },
  {
    id: 'boutsen', fullName: 'Thierry Boutsen', givenName: 'Thierry', familyName: 'Boutsen',
    nationality: 'Belgian', nationalityCode: 'be',
    teams: ['Williams'],
    isChampion: false, winsAtLeastOne: true, totalWins: 3, totalGPs: 163,
    decades: ['80s', '90s'], isLatam: false,
    wikipediaName: 'Thierry_Boutsen',
  },
  {
    id: 'brundle', fullName: 'Martin Brundle', givenName: 'Martin', familyName: 'Brundle',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Tyrrell', 'McLaren', 'Brabham'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 165,
    decades: ['80s', '90s'], isLatam: false,
    wikipediaName: 'Martin_Brundle',
  },
  {
    id: 'warwick', fullName: 'Derek Warwick', givenName: 'Derek', familyName: 'Warwick',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Renault', 'Brabham'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 147,
    decades: ['80s', '90s'], isLatam: false,
    wikipediaName: 'Derek_Warwick',
  },
  {
    id: 'patrese', fullName: 'Riccardo Patrese', givenName: 'Riccardo', familyName: 'Patrese',
    nationality: 'Italian', nationalityCode: 'it',
    teams: ['Brabham', 'Williams'],
    isChampion: false, winsAtLeastOne: true, totalWins: 6, totalGPs: 257,
    decades: ['80s', '90s'], isLatam: false,
    wikipediaName: 'Riccardo_Patrese',
  },
  // ── 70s/80s era ───────────────────────────────────────────────────────────
  {
    id: 'reutemann', fullName: 'Carlos Reutemann', givenName: 'Carlos', familyName: 'Reutemann',
    nationality: 'Argentine', nationalityCode: 'ar',
    teams: ['Brabham', 'Ferrari', 'Lotus', 'Williams'],
    isChampion: false, winsAtLeastOne: true, totalWins: 12, totalGPs: 146,
    decades: ['70s', '80s'], isLatam: true,
    wikipediaName: 'Carlos_Reutemann',
  },
  {
    id: 'regazzoni', fullName: 'Clay Regazzoni', givenName: 'Clay', familyName: 'Regazzoni',
    nationality: 'Swiss', nationalityCode: 'ch',
    teams: ['Ferrari', 'Tyrrell', 'Williams', 'Brabham'],
    isChampion: false, winsAtLeastOne: true, totalWins: 5, totalGPs: 132,
    decades: ['70s', '80s'], isLatam: false,
    wikipediaName: 'Clay_Regazzoni',
  },
  {
    id: 'watson', fullName: 'John Watson', givenName: 'John', familyName: 'Watson',
    nationality: 'British', nationalityCode: 'gb',
    teams: ['Brabham', 'McLaren'],
    isChampion: false, winsAtLeastOne: true, totalWins: 5, totalGPs: 152,
    decades: ['70s', '80s'], isLatam: false,
    wikipediaName: 'John_Watson_(racing_driver)',
  },
  {
    id: 'laffite', fullName: 'Jacques Laffite', givenName: 'Jacques', familyName: 'Laffite',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Tyrrell', 'Williams', 'McLaren', 'Brabham'],
    isChampion: false, winsAtLeastOne: true, totalWins: 6, totalGPs: 176,
    decades: ['70s', '80s'], isLatam: false,
    wikipediaName: 'Jacques_Laffite',
  },
  {
    id: 'arnoux', fullName: 'René Arnoux', givenName: 'René', familyName: 'Arnoux',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Renault', 'Ferrari'],
    isChampion: false, winsAtLeastOne: true, totalWins: 7, totalGPs: 149,
    decades: ['70s', '80s'], isLatam: false,
    wikipediaName: 'René_Arnoux',
  },
  {
    id: 'rosberg_k', fullName: 'Keke Rosberg', givenName: 'Keke', familyName: 'Rosberg',
    nationality: 'Finnish', nationalityCode: 'fi',
    teams: ['Williams', 'McLaren'],
    isChampion: true, winsAtLeastOne: true, totalWins: 5, totalGPs: 114,
    decades: ['80s'], isLatam: false,
    wikipediaName: 'Keke_Rosberg',
  },
  {
    id: 'fittipaldi', fullName: 'Emerson Fittipaldi', givenName: 'Emerson', familyName: 'Fittipaldi',
    nationality: 'Brazilian', nationalityCode: 'br',
    teams: ['Lotus', 'McLaren', 'Brabham'],
    isChampion: true, winsAtLeastOne: true, totalWins: 14, totalGPs: 144,
    decades: ['70s', '80s'], isLatam: true,
    wikipediaName: 'Emerson_Fittipaldi',
  },
  {
    id: 'scheckter', fullName: 'Jody Scheckter', givenName: 'Jody', familyName: 'Scheckter',
    nationality: 'South African', nationalityCode: 'za',
    teams: ['Tyrrell', 'Ferrari'],
    isChampion: true, winsAtLeastOne: true, totalWins: 10, totalGPs: 112,
    decades: ['70s'], isLatam: false,
    wikipediaName: 'Jody_Scheckter',
  },
  {
    id: 'alboreto', fullName: 'Michele Alboreto', givenName: 'Michele', familyName: 'Alboreto',
    nationality: 'Italian', nationalityCode: 'it',
    teams: ['Tyrrell', 'Ferrari'],
    isChampion: false, winsAtLeastOne: true, totalWins: 5, totalGPs: 215,
    decades: ['80s', '90s'], isLatam: false,
    wikipediaName: 'Michele_Alboreto',
  },
  {
    id: 'tambay', fullName: 'Patrick Tambay', givenName: 'Patrick', familyName: 'Tambay',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Tyrrell', 'Ferrari'],
    isChampion: false, winsAtLeastOne: true, totalWins: 2, totalGPs: 114,
    decades: ['80s'], isLatam: false,
    wikipediaName: 'Patrick_Tambay',
  },
  {
    id: 'pironi', fullName: 'Didier Pironi', givenName: 'Didier', familyName: 'Pironi',
    nationality: 'French', nationalityCode: 'fr',
    teams: ['Tyrrell', 'Ferrari'],
    isChampion: false, winsAtLeastOne: true, totalWins: 3, totalGPs: 73,
    decades: ['80s'], isLatam: false,
    wikipediaName: 'Didier_Pironi',
  },
  {
    id: 'jos_verstappen', fullName: 'Jos Verstappen', givenName: 'Jos', familyName: 'Verstappen',
    nationality: 'Dutch', nationalityCode: 'nl',
    teams: ['Benetton', 'Tyrrell'],
    isChampion: false, winsAtLeastOne: false, totalWins: 0, totalGPs: 107,
    decades: ['90s', '2000s'], isLatam: false,
    wikipediaName: 'Jos_Verstappen',
  },
  // ── 50s/60s era ───────────────────────────────────────────────────────────
  {
    id: 'fangio', fullName: 'Juan Manuel Fangio', givenName: 'Juan Manuel', familyName: 'Fangio',
    nationality: 'Argentine', nationalityCode: 'ar',
    teams: ['Alfa Romeo', 'Ferrari', 'Mercedes'],
    isChampion: true, winsAtLeastOne: true, totalWins: 24, totalGPs: 52,
    decades: ['50s'], isLatam: true,
    wikipediaName: 'Juan_Manuel_Fangio',
  },
  {
    id: 'gonzalez_jf', fullName: 'José Froilán González', givenName: 'José Froilán', familyName: 'González',
    nationality: 'Argentine', nationalityCode: 'ar',
    teams: ['Ferrari'],
    isChampion: false, winsAtLeastOne: true, totalWins: 2, totalGPs: 26,
    decades: ['50s'], isLatam: true,
    wikipediaName: 'José_Froilán_González',
  },
];
